api_version = "2026-01"

[[extensions]]
name = "Territory Management"
handle = "territory-management"
uid = "a69ad545-35b8-769b-413c-e41a423122b4bae0da9c"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/TerritoryBlock.tsx"
target = "admin.company-details.block.render"
