export * from './errors';

// Re-export shared types for convenience
export type {
  Shop,
  ShopConfig,
  PaymentStrategy,
  SalesRep,
  SalesRepListItem,
  SalesRepWithTerritories,
  CreateSalesRepRequest,
  UpdateSalesRepRequest,
  RepRole,
  Territory,
  TerritoryWithZipcodes,
  TerritoryListItem,
  CreateTerritoryRequest,
  UpdateTerritoryRequest,
  Company,
  CompanyListItem,
  CompanyLocation,
  CompanyContact,
  CreateCompanyRequest,
  CreateCompanyLocationRequest,
  CreateCompanyContactRequest,
  UpdateCompanyRequest,
  PaymentTerms,
  CartSession,
  CartLineItem,
  CartStatus,
  CartSummary,
  Order,
  OrderListItem,
  PaymentMethod,
  PaymentMethodDisplay,
  JWTPayload,
  LoginRequest,
  LoginResponse,
  ApiResult,
  ApiResponse,
  ApiError,
  PaginatedResponse,
  PaginationParams,
  SearchParams,
  // Products
  Product,
  ProductVariant,
  ProductWithVariants,
  ProductListItem,
  ProductVariantListItem,
  ProductStatus,
  // Promotions
  Promotion,
  PromotionListItem,
  PromotionType,
  CreatePromotionRequest,
  UpdatePromotionRequest,
  AppliedPromotion,
  LineItemDiscount,
} from '@field-sales/shared';
