# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ace764e1521a6d126490f8dcdfd74c2"
name = "Field Sales Manager"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "companies/create", "companies/update", "companies/delete" ]
  uri = "/webhooks/companies"

  [[webhooks.subscriptions]]
  topics = [
  "company_locations/update",
  "company_locations/delete",
  "company_locations/create"
]
  uri = "/webhooks/company-locations"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_companies,read_customers,read_orders,write_companies,write_draft_orders,write_orders,read_customer_payment_methods,write_payment_mandate"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
